import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { YoptaEditor } from 'yopta-editor';
import { useState } from 'react';
import { Descendant } from 'slate';

export default function Home() {
  const [value, setState] = useState<Descendant[]>();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <YoptaEditor shouldStoreInLocalStorage value={value} onChange={(val) => setState(val)} />
      </div>
    </div>
  );
}
