import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { YoptaEditor } from 'yopta-editor';
import { useState } from 'react';
import { Descendant } from 'slate';
import { uploadToCloudinary } from '../utils';

export default function Home() {
  const [value, setState] = useState<Descendant[]>();

  const onChangeMedia = async (file: File, type: string) => {
    const { url, data } = await uploadToCloudinary(file, type);
    return { url, options: data };
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <YoptaEditor
          value={value}
          wrapCls={styles.editorWrapper}
          onChange={(val: Descendant[]) => setState(val)}
          shouldStoreInLocalStorage
          media={{
            imageProps: {
              onChange: (file: File) => onChangeMedia(file, 'image'),
            },
            videoProps: {
              onChange: (file: File) => onChangeMedia(file, 'video'),
            },
          }}
        />
      </div>
    </div>
  );
}
