export const ELEMENT_TYPES_MAP = {
  'block-quote': 'block-quote',
  'bulleted-list': 'bulleted-list',
  'numbered-list': 'numbered-list',
  'list-item': 'list-item',
  'heading-one': 'heading-one',
  'heading-two': 'heading-two',
  'heading-three': 'heading-three',
  link: 'link',
  image: 'image',
  video: 'video',
  paragraph: 'paragraph',
  callout: 'callout',
  code: 'code',
  embed: 'embed',
};
