name: 🐛 Bug
description: Report an issue to help improve the project.
title: "[BUG] <description>"
labels: ["🛠 goal: fix", "🚦 status: awaiting triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report! You can also join our Discord community [here](https://discord.gg/Dt8rhSTjsn) 🦄
  - type: checkboxes
    id: duplicates
    attributes:
      label: Has this bug been raised before?
      description: Increase the chances of your issue being accepted by making sure it has not been raised before.
      options:
        - label: I have checked "open" AND "closed" issues and this is not a duplicate
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug you have found. Please include relevant information and resources (for example the steps to reproduce the bug)
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: dropdown
    id: assignee
    attributes:
      label: Do you want to work on this issue?
      multiple: false
      options:
        - "No"
        - "Yes"
      default: 0
    validations:
      required: false
