name: 📦 Plugin Request
description: Have an idea of a useful plugin to implement? Let us know...
title: "[PLUGIN] <description>"
labels: ["⭐ goal: addition", "🚦 status: awaiting triage", "📦 plugin"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this plugin request! You can also join our Discord community [here](https://discord.gg/Dt8rhSTjsn) 🦄
  - type: checkboxes
    id: duplicates
    attributes:
      label: Is this a unique plugin request?
      description: Increase the chances of your issue being accepted by making sure it has not been raised before.
      options:
        - label: I have checked "open" AND "closed" issues and this is not a duplicate
          required: true
  - type: textarea
    id: description
    attributes:
      label: Proposed Plugin Solution
      description: A clear description of the enhancement you propose. Please include relevant information and resources (for example another project's implementation of this feature).
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots/mockups of how the plugin could operate visually.
    validations:
      required: false
  - type: dropdown
    id: assignee
    attributes:
      label: Do you want to work on this issue?
      multiple: false
      options:
        - "No"
        - "Yes"
      default: 0
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: If "yes" to the above, please explain how you would technically implement this (issue will not be assigned if this is skipped)
      description: For example reference any existing code or library
    validations:
      required: false
