import Head from 'next/head';
import styles from '../../styles/Home.module.scss';
import { YoptaEditor } from 'yopta-editor';
import { useState } from 'react';
import { Descendant } from 'slate';
import { uploadToCloudinary } from '../../utils';

export default function Home() {
  const [editorValue, setEditorValue] = useState<Descendant[]>();

  const onChangeMedia = async (file: File, type: string) => {
    const { url, data } = await uploadToCloudinary(file, type);
    return { url, options: data };
  };

  const media = {
    imageProps: {
      onChange: (file: File) => onChangeMedia(file, 'image'),
      accept: 'image/*',
    },
    videoProps: {
      onChange: (file: File) => onChangeMedia(file, 'video'),
    },
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <YoptaEditor
          value={editorValue}
          wrapCls={styles.editorWrapper}
          onChange={(val: Descendant[]) => setEditorValue(val)}
          media={media}
          shouldStoreInLocalStorage={{ name: 'example-content' }}
        />
      </div>
    </div>
  );
}
